spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order_db_m
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update  # use "create" if needed, but uncomment manually
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
